[package]
name = "proclet-utils-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proclet = { path = "../proclet", default-features = false, features = ["literal-value"] }
