[package]
name = "proclet-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
proclet = { path = "../proclet", default-features = false }
proclet-utils-macros = { path = "../proclet-utils-macros" }
